<a href="https://colab.research.google.com/github/khansao0/Praktikum-AVD-C2-Netflix-untuk-strategi-bisnis/blob/main/Checkpoint_1_AVD_C2_Qonitah_Khansa'_Ayu_Madani_Alamsyah_2509116113.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Analisis Tren Konten Netflix untuk Mendukung Strategi Bisnis**

# **Import Library**

In [3]:
import pandas as pd

# **Memuat Dataset**

In [7]:
path = "/content/drive/MyDrive/avd/netflix_titles.csv"
df = pd.read_csv(path)

**ngecek jumlah baris dan kolom dataset**

In [9]:
df.shape

(8807, 12)

In [15]:
df = pd.read_csv(path)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [11]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [14]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

# **Business Understanding**

Fokus utama pada tahap ini adalah memahami
permasalahan bisnis, tujuan yang ingin dicapai,
serta kebutuhan solusi dari sudut pandang bisnis. Nah saya mengambil judul **"Analisis tren konten Netflix untuk strategi bisnis"**. Netflix bukan cuman sekedar platform streaming, tapi udah jadi salah satu utama penting di dunia industri hiburan global. Maka dari itu saya mengambil judul ini untuk ngebayangin gimana Netflix ngatur strategi bisnisnya.

 **Business Objective**

Dataset yang saya gunakan adalah Netflix Shows Dataset dari Kaggle. Data ini berisi informasi mengenai judul konten, jenis konten Movie atau TV Show, negara asal produksi, tahun rilis, genre, serta durasi. Dengan dataset ini, kita akan membantu untuk memahami, mengevaluasi, serta menganalisis tren konten Netflix berdasarkan karakteristik seperti genre, tahun rilis, dan negara produksi.

Tujuan nya : Netflix pengen tau tren konten yang paling diminati oleh para streaming atau audiens apa yang lebih banyak orang nonton atau minati. Apakah orang bakal lebih banyak nonton TV Show daripada movie, atau genre apa yang lagi naik daun, atau negara mana yang lebih banyak/aktif bikin konten. Dengan insight yang saya buat ini, Netflix bisa lebih gampang juga nentuin kemana arah bisnis nya, entah itu mau inves lebih banyak di genre thriller atau perluas produksi di negara tertentu.

**Assess Situation**

Dataset berisi ribuan baris data dengan informasi judul, tipe konten, negara, tahun rilis, genre, dan durasi. Tapi seperti biasa, data ngga selalu sempurna. Jadi ada missing values di kolom country dan rating, yang bikin kita harus berhati-hati. Meskipun begitu tetap ada peluang besar, yang bisa bikin visualisasi tren genre dari tahun ke tahun, distribusi konten per negara, bahkan perkembangan jumlah produksi. Jadi, meskipun data sangat bagus, tapi ada bagian cacatnya. Maka dari itu perlu adanya pemeriksaan lebih lanjut pada tahap berikutnya.

**Analytic Goals and Project Plan**

**Analytic Goals**

Di dalam data set ini ada target analisis untuk strategi bisnis :



*   Menemukan genre yang paling sering muncul dan paling populer. Kalau genre drama ternyata mendominasi, berarti Netflix bisa terus push konten drama.

*   Melihat tren jumlah konten per tahun. Apakah produksi makin naik tiap tahun, atau ada tahun tertentu yang drop? Itu bisa jadi indikator kondisi industri hiburan global.

*   Menganalisis distribusi konten berdasarkan negara. Kalau India atau Korea Selatan ternyata punya kontribusi besar, Netflix bisa lebih fokus kolaborasi dengan industri film di sana.

**Project Plan**



1.   Memahami isi dataset : jumlah baris, kolom, tipe data.
2.   Membersihkan data dari missing values dan duplikasi.
3.   Melakukan eksplorasi data dengan visualisasi tren dari genre, tahun rilis, dan negara.
4.   Menyusun insight dan rekomendasi yang oke atau relevan untuk strateegi bisnis Netflix.

Jadi lebih ke : Kumpulin data, pahami konteks (business understanding), bersihin data, analisis tren, lalu kasih rekomendasi yang bisa dipakai buat keputusan bisnis.